### ISSUE TITLE
Info not updated onChangeState

### ISSUE THREAD

**Issue by tokybe** [2fdevs/bower-videogular-analytics#2]
It would be nice if info.category and info.label can be updated in the onChangeState function. They are set just once in the addWatchers function.

**Comment by 2fdevs** [comment]
Hi, thanks for your feedback.

You should open your suggestions on the main repository, this is only for distribution on bower.

https://github.com/2fdevs/videogular

**Comment by tokybe** [comment]
Ok, I'll do that. Thanks!
