### ISSUE TITLE
Progress percentage calculation is incorrect (inverted)

### ISSUE THREAD

**Issue by nmstoker** [2fdevs/bower-videogular-analytics#7]
Hello,

When dealing with events to indicate that a viewer has reached a certain point of progress, there seems to be a problem.  The calculation for Progress looks like it is inversely proportional to the correct one.  I expect it is because with the example chosen of 10 (== 10%) it still comes out correct, because dividing a time into 10 pieces means each is 10% of the total, but as soon as you try other values, you'll see that it fails.

For instance I ran it with 20 and found that it was reporting far too frequently and logged events of 120%, 140% etc!

Fortunately the solution is simple and just one line. I've included it below.  Is this something you could apply?

This line in vg-analytics.js:

  `var progressJump = Math.floor(totalMiliseconds / scope.vgTrackInfo.events.progress);`

should be replaced by:

  `var progressJump = Math.floor(totalMiliseconds * scope.vgTrackInfo.events.progress / 100);`

Many thanks,
Neil

**Comment by nmstoker** [comment]
PS If you prefer me to raise this in the main Videogular repo, just say the word and I'll do so! It just struck me that this was closest to the actual problem in this case.
Thanks!

**Comment by Elecash** [comment]
Yes, please, this repo is only for distribution.

Thanks.
